spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
token:
  exp:
    access: ${ACCESS_TOKEN} # 1800ms * 1000 == 30min
    refresh : ${REFRESH_TOKEN} # 43200ms * 1000 = 1 week
  secret: ${SECRET}