spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
      url: ${S3_URL}
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ${REGION}
      auto: false
    stack:
      auto: false
server:
  port: 8080
token:
  secret: ${SECRET}
  exp:
    access: ${ACCESS_EXPIRED} # 1800ms * 1000 == 30min
    refresh : ${REFRESH_EXPIRED} # 604800ms * 1000 = 1 week